version: '3'

services:
  mdcx:
    image: stainless403/mdcx:latest
    container_name: ${CONTAINER_NAME}
    volumes:
      # 建议将配置文件映射出来，升级后可继续使用。
      - ./config/config.ini:/app/config.ini
      # 更多配置文件
      # - ./config/config2.ini:/app/config2.ini
      # - ./config/config3.ini:/app/config3.ini

      # 添加一些需要的映射，比如你的影片所在位置
      - /path/to/jav:/jav:rslave
    environment:
      - TZ=${TZ}
      # 应用窗口宽度
      - DISPLAY_WIDTH=${DISPLAY_WIDTH}
      # 应用窗口高度
      - DISPLAY_HEIGHT=${DISPLAY_HEIGHT}
      # 访问密码
      - VNC_PASSWORD=${VNC_PASSWORD}
    ports:
      - ${WEB_LISTENING_PORT}:5800
      - ${VNC_LISTENING_PORT}:5900
    restart: unless-stopped
    network_mode: bridge
    stdin_open: true
